~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-29.png ../Images.xcassets/AppIcon.appiconset/Icon-29.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-29@2x.png ../Images.xcassets/AppIcon.appiconset/Icon-29@2x.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-40@2x.png ../Images.xcassets/AppIcon.appiconset/Icon-40@2x.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-60@2x.png ../Images.xcassets/AppIcon.appiconset/Icon-60@2x.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-76.png ../Images.xcassets/AppIcon.appiconset/Icon-76.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-76@2x.png ../Images.xcassets/AppIcon.appiconset/Icon-76@2x.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-83.5@2x.png ../Images.xcassets/AppIcon.appiconset/Icon-83.5@2x.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-512.png ../Images.xcassets/AppIcon.appiconset/Icon-512.png
~/tools/pngcrush-1.8.13/pngcrush -c 2 -brute Icon-1024.png ../Images.xcassets/AppIcon.appiconset/Icon-1024.png
